package service.universityComparators;

public enum UniversityComparators {
    UNIVERSITY_FOUNDATION_YEAR_COMPARATOR,
    UNIVERSITY_ID_COMPARATOR,
    UNIVERSITY_NAME_COMPARATOR,
    UNIVERSITY_SHORT_NAME_COMPARATOR,
    UNIVERSITY_PROFILE_COMPARATOR
}
